### ISSUE TITLE
Form Resubmission

### ISSUE THREAD

**Issue by tjg17** [Bumpworks/bumpsite#18]
When the form reloads the page, it will resubmit the last game that was entered even if the text box is empty. Is there a way to clear the form explicitly after submitting the game?

![image](https://cloud.githubusercontent.com/assets/4998049/11338361/9c36c726-91c1-11e5-8969-009856af26b7.png)

**Comment by KaighnKevlin** [comment]
Whatcha mean?

So you 1) enter Tyler Shaunak
2) hit submit
3) page reloads after submitting
4) hit submit again?

**Comment by tjg17** [comment]
I can show in person tonight, but steps to recreate problem are:

1) Add some games
2) Refresh the page when the text box is empty (after it has already reloaded after submitting)
3) Hit continue on the chrome pop up box
4) Your games from previous submission will be duplicated

**Comment by tjg17** [comment]
@KaighnKevlin This may be helpful: http://stackoverflow.com/questions/5823580/django-form-resubmitted-upon-refresh

**Comment by tjg17** [comment]
Just pulled the latest commits and this issue is still happening

**Comment by tjg17** [comment]
This seems to be working now - must not have restarted the server when I was checking it earlier.
