### ISSUE TITLE
Game Feed is not listed chronologically

### ISSUE THREAD

**Issue by tjg17** [Bumpworks/bumpsite#39]
![image](https://cloud.githubusercontent.com/assets/4998049/11673822/c28da0f0-9de9-11e5-8969-6875bf3a4601.png)

The submit game page is listed correct chronologically:

![image](https://cloud.githubusercontent.com/assets/4998049/11673832/ccdda1c2-9de9-11e5-9db3-76a2d79b25c0.png)

**Comment by tjg17** [comment]
Note this is only really a problem if multiple lines of games are entered in the submit game form that all have the same timestamp

**Comment by KaighnKevlin** [comment]
http://stackoverflow.com/questions/34246405/django-order-by-datetime

**Comment by KaighnKevlin** [comment]
This could be a problem for rankings
